name: Build Custom Fedora ISO

on:
  push:
    branches: [ "main" ] # Runs automatically when you push updates
  workflow_dispatch:     # Lets you trigger the build manually via GitHub website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Live ISO via Livemedia Creator
        uses: jasonn3/build-fedora-iso-action@v1
        with:
          kickstart: custom-fedora.ks
          filename: custom-fedora-dev-remix.iso

      - name: Upload Bootable Operating System
        uses: actions/upload-artifact@v4
        with:
          name: fedora-dev-iso
          path: ./custom-fedora-dev-remix.iso
          retention-days: 5 # Saves the file on GitHub for 5 days

